### PR TITLE
Creating a new workspace using API

### PR DESCRIPTION
**Pull request by OleksSokolov**
[related issue](https://github.com/equinor/flowify-workflows-server/issues/45)

### CODE REVIEW

**Comment by OleksSokolov** [comment]
Example for testing
Screenshot 2023-02-15 at 23 37 51


URL:  POST http://localhost:8080/flowify-server/api/v1/workspaces/ 
Body: 
`{
    "Name":"new-workspace", "Roles":["sandbox-developer"]
}`

**Comment by adamchengtkc** [comment]
Does it allow specifying admin and user role in a workspace?

**Comment by OleksSokolov** [comment]
> Does it allow specifying admin and user role in a workspace?

@adamchengtkc no I believe specifying admin and user roles in workspaces is a separate [issue](https://github.com/equinor/flowify-workflows-server/issues/41)

**Comment by adamchengtkc** [comment]
If I remember correctly, the admin role is already implemented (i.e user cannot access the secret page). Currently, the backend look for a "-admin" suffix in the role to determine role of a user. So in your example above. the backend currently will look for "sandbox-developer-admin" for admin role.

there is nothing wrong with this PR. Just to clarify the current implementation

**Review by adamchengtkc — APPROVED** [review]

**Comment by OleksSokolov** [comment]
@adamchengtkc Thanks for the clarification, I understood the question now. You are absolutely right and yes it allows specifying admin and user roles in the new workspace

**Pull request merged**
